# Generated by Django 4.2.7 on 2024-12-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorDesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (Arabic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interior Design Project',
                'verbose_name_plural': 'Interior Design Projects',
            },
        ),
        migrations.CreateModel(
            name='InteriorDesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interior_design/')),
                ('alt_en', models.CharField(blank=True, max_length=200, verbose_name='Alt Text (English)')),
                ('alt_ar', models.CharField(blank=True, max_length=200, verbose_name='Alt Text (Arabic)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.interiordesignproject')),
            ],
            options={
                'verbose_name': 'Interior Design Image',
                'verbose_name_plural': 'Interior Design Images',
                'ordering': ['order'],
            },
        ),
    ]
