# Generated by Django 4.2.7 on 2024-12-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_interiordesignproject_interiordesignimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiordesignproject',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('hospitality', 'Hospitality')], default='residential', max_length=50, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interiordesignproject',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interior_projects', to='main.teammember', verbose_name='Designer'),
        ),
    ]
