# Generated by Django 4.2.7 on 2024-12-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_interiordesignproject_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='education_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='short_desc_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='short_desc_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
