# Generated by Django 4.2.7 on 2024-12-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_teammember_education_ar_teammember_education_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio_ar',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='github',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='youtube',
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='social_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='social_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='social_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='social_twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='team_members/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_ar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
    ]
